name: lfm-app
services:
  - name: web
    github:
      repo: dmitrymomot/lfm
      branch: develop
      deploy_on_push: true
    build_command: npm install && npm run build-prod
    http_port: 8080
    routes:
      - /
    health_check:
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 2
      failure_threshold: 2
      http_path: /health
    envs:
      - key: APP_PORT
        value: "8080"
      - key: APP_BASE_URL
        value: http://localhost
      - key: DEBUG_MODE
        value: "true"
      - key: HEALTH_ENDPOINT
        value: /health
      - key: TEMPLATE_DIR
        value: ./src/views
      - key: FORM_CONFIG_PATH
        value: ./form.config.yaml
      - key: STATIC_FILES_DIR
        value: ./src/assets

domains:
  domain: your-domain.com
