# TODO: set up valid domain
# domains:
#   - domain: testapp.yourdomain.com
#     type: PRIMARY
#     zone: yourdomain.com # optional
#     wildcard: false

name: testapp
services:
  - name: web
    github:
      repo: dmitrymomot/testapp
      branch: master
      deploy_on_push: true
    # build_command: npm install && npm run build-prod
    http_port: 8080
    routes:
      - path: /
    health_check:
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 2
      failure_threshold: 2
      http_path: /health
    envs:
      - key: APP_PORT
        value: "8080" # the same as in http_port parameter
      - key: APP_BASE_URL
        value: https://testapp.yourdomain.com # the same as in domain section
      - key: DEBUG_MODE
        value: "true"
      - key: HEALTH_ENDPOINT
        value: /health
      - key: TEMPLATE_DIR
        value: ./src/views
      - key: FORM_CONFIG_PATH
        value: ./form.config.yaml
      - key: STATIC_FILES_DIR
        value: ./src/assets
